redis:
  enabled: true
  host: redis-stack
  port: "6379"
  username: ""
  password: ""
  ssl: false

context7:
  enabled: true

github:
  enabled: true
  personal_access_token: <GITHUB_PERSONAL_ACCESS_TOKEN>

markitdown:
  enabled: true
  paths:
    - /workspace

falkordb:
  enabled: true

h9s-ingest:
  enabled: true
